var { runTestGroup } = require('../helpers.js');

runTestGroup({
  name: 'Trashi Gyepa',
  includeInPercentage: true,
  sentences: true,
  tests: [
    { tibetan: 'ༀ།', converted: "om" },
    { tibetan: 'སྣང་སྲིད་རྣམ་དག་རང་བཞིན་ལྷུན་གྲུབ་པའི། །', converted: "nangsi namtak rangzhin lhüntrup pé"  },
    { tibetan: 'བཀྲ་ཤིས་ཕྱོགས་བཅུའི་ཞིང་ན་བཞུགས་པ་ཡི། །', converted: "trashi chokchü zhing-na zhukpa yi" },
    { tibetan: 'སངས་རྒྱས་ཆོས་དང་དགེ་འདུན་འཕགས་པའི་ཚོགས། །', converted: "sang-gyé chötang gendün p'akpé tsok" },
    { tibetan: 'ཀུན་ལ་ཕྱག་འཚལ་བདག་ཅག་བཀྲ་ཤིས་ཤོག །', converted: "künla chaktsal dachak trashi sho" },
    { tibetan: 'སྒྲོལ་མའི་རྒྱལ་པོ་རྩལ་བརྟན་དོན་གྲུབ་དགོངས། །', converted: "drölmé gyalpo tsalten töntrup gong" },
    { tibetan: 'བྱམས་པའི་རྒྱན་དཔལ་དགེ་གྲགས་དཔལ་དམ་པ། །', converted: "champé gyenpal gétrak paltam pa" },
    { tibetan: 'ཀུན་ལ་དགོངས་པ་རྒྱ་ཆེར་གྲགས་པ་ཅན། །', converted: "künla gongpa gyacher trakpa chen"  },
    { tibetan: 'ལྷུན་པོ་ལྟར་འཕགས་རྩལ་གྲགས་དཔལ་དང་ནི། །', converted: "lhünpo tarp'ak tsaltrak paltang ni" },
    { tibetan: 'སེམས་ཅན་ཐམས་ཅད་ལ་དགོངས་གྲགས་པའི་དཔལ། །', converted: "semchen thamché lagong trakpé pal" },
    { tibetan: 'ཡིད་ཚིམ་མཛད་པ་རྩལ་རབ་གྲགས་དཔལ་ཏེ། །', converted: "yitsim dzépa tsalrap trakpal té"  },
    { tibetan: 'མཚན་ཙམ་ཐོས་པས་བཀྲ་ཤིས་དཔལ་འཕེལ་བ། །', converted: "tsentsam thöpé trashi palp'el wa" },
    { tibetan: 'བདེ་བར་གཤེགས་པ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', converted: "déwar shekpa gyéla chaktsal lo" },
    { tibetan: 'འཇམ་དཔལ་གཞོན་ནུ་དཔལ་ལྡན་རྡོ་རྗེ་འཛིན། །', converted: "jampal zhön-nu palden dorjé dzin" },
    { tibetan: 'སྤྱན་རས་གཟིགས་དབང་མགོན་པོ་བྱམས་པའི་དཔལ། །', converted: "chenré ziwang gönpo champé pal", pending: true },
    { tibetan: 'ས་ཡི་སྙིང་པོ་སྒྲིབ་པ་རྣམ་པར་སེལ། །', converted: "sayi nyingpo drip-pa nampar sel" },
    { tibetan: 'ནམ་མཁའི་སྙིང་པོ་འཕགས་མཆོག་ཀུན་ཏུ་བཟང་། །', converted: "namkhé nyingpo p'akchok küntu zang" },
    { tibetan: 'ཨུཏྤལ་རྡོ་རྗེ་པད་དཀར་ཀླུ་ཤིང་དང་། །', converted: "utpal dorjé pékar lushing tang" },
    { tibetan: 'ནོར་བུ་ཟླ་བ་རལ་གྲི་ཉི་མ་ཡི། །', converted: "norpu dawa raltri nyima yi" },
    { tibetan: 'ཕྱག་མཚན་ལེགས་བསྣམས་བཀྲ་ཤིས་དཔལ་གྱི་མཆོག །', converted: "chaktsen leknam trashi palkyi chok" },
    { tibetan: 'བྱང་ཆུབ་སེམས་དཔའ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', converted: "changchup sempa gyéla chaktsal lo" },
    { tibetan: 'རིན་ཆེན་གདུགས་མཆོག་བཀྲ་ཤིས་གསེར་གྱི་ཉ། །', converted: "rinchen dukchok trashi serkyi nya" },
    { tibetan: 'འདོད་འབྱུང་བུམ་བཟང་ཡིད་འོང་ཀ་མ་ལ། །', converted: "döjung pumzang yi-ong kama la" },
    { tibetan: 'སྙན་གྲགས་དུང་དང་ཕུན་ཚོགས་དཔལ་བེའུ། །', converted: "nyentrak tungtang p'üntsok palpé-u" },
    { tibetan: 'མི་ནུབ་རྒྱལ་མཚན་དབང་བསྒྱུར་འཁོར་ལོ་སྟེ། །', converted: "minup gyaltsen wang-gyur khorlo té"  },
    { tibetan: 'རིན་ཆེན་རྟགས་མཆོག་བརྒྱད་ཀྱི་ཕྱག་མཚན་ཅན། །', converted: "rinchen takchok gyékyi chaktsen chen"  },
    { tibetan: 'ཕྱོགས་དུས་རྒྱལ་བ་མཆོད་ཅིང་དགྱེས་བསྐྱེད་མ། །', converted: "choktü gyalwa chöching gyékyé ma" },
    { tibetan: 'སྒེགས་སོགས་ངོ་བོ་དྲན་པའི་དཔལ་འཕེལ་བ། །', converted: "geksok ngowo trenpé palp'el wa" },
    { tibetan: 'བཀྲ་ཤིས་ལྷ་མོ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', converted: "trashi lhamo gyéla chaktsal lo" },
    { tibetan: 'ཚངས་པ་ཆེན་པོ་བདེ་འབྱུང་སྲེད་མེད་བུ། །', converted: "tsangpa chenpo déjung sémé pu" },
    { tibetan: 'མིག་སྟོང་ལྡན་དང་རྒྱལ་པོ་ཡུལ་འཁོར་སྲུང་། །', converted: "miktong dentang gyalpo yülkhor sung" },
    { tibetan: 'འཕགས་སྐྱེས་པོ་དང་ཀླུ་དབང་མིག་མི་བཟང་། །', converted: "p'ak-kyé potang luwang mikmi zang" },
    { tibetan: 'རྣམ་ཐོས་སྲས་ཏེ་ལྷ་རྫས་འཁོར་ལོ་དང་། །', converted: "namthö sété lhadzé khorlo tang" },
    { tibetan: 'ཏྲི་ཤུ་ལ་དང་མདུང་ཐུང་རྡོ་རྗེ་ཅན། །', converted: "trishu latang dungthung dorjé chen"  },
    { tibetan: 'པི་ཝཾ་རལ་གྲི་མཆོད་རྟེན་རྒྱལ་མཚན་འཛིན། །', converted: "piwam raltri chorten gyaltsen dzin" },
    { tibetan: 'ས་གསུམ་གནས་སུ་བཀྲ་ཤིས་དགེ་ལེགས་འཕེལ། །', converted: "sasum nésu trashi gélek p'el" },
    { tibetan: 'འཇིག་རྟེན་སྐྱོང་བ་བརྒྱད་ལ་ཕྱག་འཚལ་ལོ། །', converted: "jikten kyongwa gyéla chaktsal lo" },
    { tibetan: 'བདག་ཅག་དེང་འདིར་བྱ་བ་རྩོམ་པ་ལ། །', converted: "dachak tengdir chawa tsompa la" },
    { tibetan: 'བགེགས་དང་ཉེ་བར་འཚེ་བ་ཀུན་ཞི་ནས། །', converted: "gektang nyéwar tséwa künzhi né"  },
    { tibetan: 'འདོད་དོན་དཔལ་འཕེལ་བསམ་དོན་ཡིད་བཞིན་འགྲུབ། །', converted: "dötön palp'el samtön yizhin drup" },
    { tibetan: 'བཀྲ་ཤིས་བདེ་ལེགས་ཕུན་སུམ་ཚོགས་པར་ཤོག', converted: "trashi délek p'ünsum tsokpar sho" }
  ]
})