import { runTestGroup } from '../helpers.js';

runTestGroup({
  name: 'Prefixed mono-syllables',
  tests: [
    // Gao
    { tibetan: 'གཅའ', converted: 'cha' },
    { tibetan: 'གཉའ', converted: 'nya' },
    { tibetan: 'གཏའ', converted:  'ta' },
    { tibetan: 'གདའ', converted:  'da' },
    { tibetan: 'གནའ', converted:  'na' },
    { tibetan: 'གཙའ', converted: 'tsa' },
    { tibetan: 'གཞའ', converted: 'zha' },
    { tibetan: 'གཟའ', converted:  'za' },
    { tibetan: 'གཡའ', converted:  'ya' },
    { tibetan: 'གཤའ', converted: 'sha' },
    { tibetan: 'གསའ', converted:  'sa' },

    // Dao
    { tibetan: 'དཀའ', converted:  'ka' },
    { tibetan: 'དགའ', converted:  'ga' },
    { tibetan: 'དངའ', converted: 'nga' },
    { tibetan: 'དཔའ', converted:  'pa' },
    { tibetan: 'དབའ', converted:  'wa' },
    { tibetan: 'དམའ', converted:  'ma' },
    { tibetan: 'དཀྱ', converted: 'kya' },
    { tibetan: 'དགྱ', converted: 'gya' },
    { tibetan: 'དབྱ', converted:  'ya' },
    { tibetan: 'དམྱ', converted: 'nya' },
    { tibetan: 'དཀྲ', converted: 'tra' },
    { tibetan: 'དཔྲ', converted: 'tra' },
    { tibetan: 'དབྲ', converted: 'dra' },

    // Bao
    { tibetan: 'བཀའ',  converted:  'ka' },
    { tibetan: 'བགའ',  converted:  'ga' },
    { tibetan: 'བཅའ',  converted: 'cha' },
    { tibetan: 'བཏའ',  converted:  'ta' },
    { tibetan: 'བདའ',  converted:  'da' },
    { tibetan: 'བཙའ',  converted: 'tsa' },
    { tibetan: 'བཞའ',  converted: 'zha' },
    { tibetan: 'བཟའ',  converted:  'za' },
    { tibetan: 'བཤའ',  converted: 'sha' },
    { tibetan: 'བསའ',  converted:  'sa' },
    { tibetan: 'བཀྱ',  converted: 'kya' },
    { tibetan: 'བགྱ',  converted: 'gya' },
    { tibetan: 'བཀྲ',  converted: 'tra' },
    { tibetan: 'བགྲ',  converted: 'dra' },
    { tibetan: 'བརླ',  converted:  'la' },
    { tibetan: 'བསླ',  converted:  'la' },
    { tibetan: 'བརྐ',  converted:  'ka' },
    { tibetan: 'བརྒ',  converted:  'ga' },
    { tibetan: 'བརྔ',  converted: 'nga' },
    { tibetan: 'བརྗ',  converted:  'ja' },
    { tibetan: 'བརྙ',  converted: 'nya' },
    { tibetan: 'བརྟ',  converted:  'ta' },
    { tibetan: 'བརྡ',  converted:  'da' },
    { tibetan: 'བརྣ',  converted:  'na' },
    { tibetan: 'བརྩ',  converted: 'tsa' },
    { tibetan: 'བརྫ',  converted: 'dza' },
    { tibetan: 'བལྟ',  converted:  'ta' },
    { tibetan: 'བསྐ',  converted:  'ka' },
    { tibetan: 'བསྒ',  converted:  'ga' },
    { tibetan: 'བསྔ',  converted: 'nga' },
    { tibetan: 'བསྙ',  converted: 'nya' },
    { tibetan: 'བསྟ',  converted:  'ta' },
    { tibetan: 'བསྡ',  converted:  'da' },
    { tibetan: 'བསྣ',  converted:  'na' },
    { tibetan: 'བསྩ',  converted: 'tsa' },
    { tibetan: 'བརྐྱ', converted: 'kya' },
    { tibetan: 'བརྒྱ', converted: 'gya' },
    { tibetan: 'བསྐྱ', converted: 'kya' },
    { tibetan: 'བསྒྱ', converted: 'gya' },
    { tibetan: 'བསྐྲ', converted: 'tra' },
    { tibetan: 'བསྒྲ', converted: 'dra' },

    // Mao
    { tibetan: 'མཁའ', converted:  'kha' },
    { tibetan: 'མགའ', converted:   'ga' },
    { tibetan: 'མངའ', converted:  'nga' },
    { tibetan: 'མཅའ', converted:  'cha' },
    { tibetan: 'མཇའ', converted:   'ja' },
    { tibetan: 'མཉའ', converted:  'nya' },
    { tibetan: 'མཐའ', converted:  'tha' },
    { tibetan: 'མདའ', converted:   'da' },
    { tibetan: 'མནའ', converted:   'na' },
    { tibetan: 'མཚའ', converted:  'tsa' },
    { tibetan: 'མཛའ', converted:  'dza' },
    { tibetan: 'མཁྱ', converted: 'khya' },
    { tibetan: 'མཀྲ', converted:  'tra' },
    { tibetan: 'མཁྲ', converted: "tr'a" },
    { tibetan: 'མགྲ', converted:  'dra' },

    // Ao
    { tibetan: 'འཁའ', converted:  'kha' },
    { tibetan: 'འགའ', converted:   'ga' },
    { tibetan: 'འཆའ', converted:  'cha' },
    { tibetan: 'འཇའ', converted:   'ja' },
    { tibetan: 'འཐའ', converted:  'tha' },
    { tibetan: 'འདའ', converted:   'da' },
    { tibetan: 'འཕའ', converted:  "p'a" },
    { tibetan: 'འབའ', converted:   'ba' },
    { tibetan: 'འཚའ', converted:  'tsa' },
    { tibetan: 'འཛའ', converted:  'dza' },
    { tibetan: 'འཁྱ', converted: 'khya' },
    { tibetan: 'འགྱ', converted:  'gya' },
    { tibetan: 'འཕྱ', converted:  'cha' },
    { tibetan: 'འབྱ', converted:   'ja' },
    { tibetan: 'འཁྲ', converted: "tr'a" },
    { tibetan: 'འགྲ', converted:  'dra' },
    { tibetan: 'འདྲ', converted:  'dra' },
    { tibetan: 'འཕྲ', converted: "tr'a" },
    { tibetan: 'འབྲ', converted:  'dra' },

    // A few cases with syllables
    { tibetan: 'བཀི',  converted:  'ki' },
    { tibetan: 'བགི',  converted:  'gi' },
    { tibetan: 'བགའ',  converted:  'ga' },
    { tibetan: 'བངི',  converted: 'ngi' },
    { tibetan: 'བཇི',  converted:  'ji' },
    { tibetan: 'བཉི',  converted: 'nyi' },
    { tibetan: 'བཏི',  converted:  'ti' },
    { tibetan: 'བདི',  converted:  'di' },
    { tibetan: 'བནི',  converted:  'ni' },
    { tibetan: 'དབི',  converted:   'i' },
    { tibetan: 'བམི',  converted:  'mi' },
    { tibetan: 'བཙི',  converted: 'tsi' },
    { tibetan: 'བཛི',  converted: 'dzi' },
  ]
})